dev_10/authapp/urls.py
import authapp.views as authapp
from django.urls import path

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
]

dev_10/dev_10/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('auth/', include('authapp.urls', namespace='authapp')),
    path('', include('mainapp.urls', namespace='mainapp')),

    path('admin/', admin.site.urls),

    path('summernote/', include('django_summernote.urls')),

]

dev_10/mainapp/urls.py
import mainapp.views as mainapp
from django.urls import path


app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('news_page/<int:pk>', mainapp.news_page, name='news_page'),
    # path('news/', mainapp.news, name='news'),

]

dev_10/mainapp/models.py
from django.db import models
from django_summernote.fields import SummernoteTextField
from datetime import date


class News(models.Model):
    title = models.CharField(verbose_name='Заголовок', max_length=128)
    text = SummernoteTextField(verbose_name='Введите текст')
    date = models.DateField(verbose_name='Дата публикации', blank=True, default=date.today)

    def __str__(self):
        return f'{self.title} - {self.date}'

    class Meta:
        ordering = ['-date']
        verbose_name = 'новость'
        verbose_name_plural = 'новости'

dev_10/authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, item in self.fields.items():
            item.widget.attrs['class'] = f'form-control {name}'


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username',
                  'password1', 'password2', 'email')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, item in self.fields.items():
            item.widget.attrs['class'] = f'form-control {name}'
            item.help_text = ''

dev_10/authapp/views.py
from django.contrib import auth
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from authapp.forms import LoginForm, RegisterForm


def login(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            auth.login(request, form.get_user())
            return HttpResponseRedirect(reverse('mainapp:index'))
    else:
        form = LoginForm()

    context = {
        'page_title': 'авторизация',
        'form': form,
    }
    return render(request, 'authapp/login.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('authapp:login'))


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('authapp:login'))
    else:
        form = RegisterForm()

    context = {
        'page_title': 'регистрация',
        'form': form,
    }
    return render(request, 'authapp/register.html', context)

dev_10/mainapp/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render

from mainapp.models import News


@login_required()
def index(request):
    news_list = News.objects.all()
    pagination = Paginator(news_list, 5)  # показывает 5 новостей
    page_number = request.GET.get('page', 1)
    page = pagination.get_page(page_number)
    is_pagination = page.has_other_pages()

    if page.has_previous():
        prev_url = '?page{}'.format(page.previous_page_number())
    else:
        prev_url = ''
    if page.has_next():
        next_url = '?page{}'.format(page.next_page_number())
    else:
        next_url = ''

    context = {
        'title': 'главная',
        'page': page,
        'is_pagination': is_pagination,
        'next_url': next_url,
        'prev_url': prev_url,
    }
    return render(request, 'mainapp/index.html', context)


def news_page(request, pk):
    news_list = News.objects.filter(id=pk)
    context = {
        'title': 'Новости',
        'news_list': news_list,
    }
    return render(request, 'mainapp/news_page.html', context)

dev_10/authapp/templates/authapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ page_title|capfirst }}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

</body>
</html>

dev_10/authapp/templates/authapp/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ page_title|capfirst }}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<div class="login-form"
     style="width: 200px; margin: 5vh auto; padding-top: 250px; margin-bottom: 25px;">
    <div class="form-title"
         style="text-align: center; font-weight: bold; font-size: larger;">Вход в систему</div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit"
               class="btn btn-success form-control text-center"
               value="Войти"
               style=" width: 200px;">
    </form>
    <br>
    <a class="btn btn-danger form-control text-center"
       style=" width: 200px;"
       href="{% url 'authapp:register' %}">
        Регистрация
    </a>
</div>
</body>
</html>

dev_10/authapp/templates/authapp/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ page_title|capfirst }}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<div class="register-form"
     style="width: 200px; margin: 5vh auto; padding-top: 250px; margin-bottom: 25px;">
    <div class="form-title"
         style="text-align: center; font-weight: bold; font-size: larger;">Регистрация</div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit"
               class="btn btn-danger form-control text-center"
               value="Зарегистрироваться"
               style=" width: 200px;">
    </form>
</div>
</body>
</html>

dev_10/mainapp/templates/mainapp/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{ title|capfirst }}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
    .page-item.active .page-link {
        background-color: black;
        border-color: black;
    }
    .page-link{
        color: black;
    }
    .navbar-light .navbar-nav .nav-link {
        font-size: 25px;
        color: black;

    }
    </style>
</head>
<body>

<nav class="navbar navbar-expand-sm bg-light navbar-light">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'mainapp:index' %}">Главная</a>
        </li>
        <li class="nav-item">
            {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'authapp:logout' %}">Выйти</a>

            {% else %}
            <a class="nav-link" href="{% url 'authapp:login' %}">Войти</a>
            {% endif %}
        </li>
    </ul>
</nav>


<section class="section bg-light">
    <div class="container">
        <div class="row justify-content-center">
            <div class="section-title mb-4">
                <h2 class="title mb-4">Все новости</h2>
            </div>
        </div>
    </div>
    {% if page %}
    {% for news in page %}
    <div class="mt-4 pt-2">
        <div class="card-body">
            <div class="col-md-12">
                <h3 class="card-title">{{ news.title }}</h3>
                <p class="card-text">{{ news.text|safe }}</p>
                <hr>
                <p class="text-black-50">Дата публикации: {{ news.date }}</p>
            </div>
        </div>
    </div>
    {% endfor %}
    {% if is_pagination %}
    <nav>
        <ul class="pagination justify-content-center">
            {% for n in page.paginator.page_range %}
            {% if page.number == n %}
            <li class="page-item active">
                <a class="page-link" href="?page={{ n }}">{{ n }}</a>
            </li>
            {% elif n > page.number|add:-3 and n < page.number|add:3 %}
            <li lass="page-link"><a class="page-link" href="?page={{ n }}">{{ n }}</a></li>
            {% endif %}
            {% endfor %}
        </ul>
    </nav>
    {% endif %}
    {% else %}
    <h1 class="m-3 text-dark text-center">Нету новостей</h1>
    {% endif %}
    </div>
</section>
</body>
</html>